name: PR
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node:
          - '14'
        platform:
          - windows-latest
        storeDir:
         - '\.pnpm-store'

    name: '${{ matrix.platform }} / Node.js v${{ matrix.node }}'
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf false
          git config --global user.name "xyz"
          git config --global user.email "x@y.z"

      - name: Checkout Commit
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        run: |
          npm install --g pnpm
          pnpm --version

      - name: Set Cache Directory
        run: 'pnpm config set store-dir ${{ matrix.storeDir }}'

      - name: Restore Cache Data
        uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: ${{ matrix.storeDir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: pnpm install

      - name: Check Code Style
        run: pnpm run lint

      - name: Build All Packages
        run: pnpm run build

      - name: Run Tests
        run: pnpm run test
